---
- name: Change hostname in victim VM
  hosts: victim
  become: true
  tasks:
    - name: Change hostname
      ansible.builtin.command:
        cmd: hostnamectl set-hostname victim
        
- name: Change hostname in attacker VM
  hosts: attacker
  become: true
  tasks:
    - name: Change hostname
      ansible.builtin.command:
        cmd: hostnamectl set-hostname attacker

- name: Change hostname in wazuh VM
  hosts: wazuh
  become: true
  tasks:
    - name: Change hostname
      ansible.builtin.command:
        cmd: hostnamectl set-hostname wazuh


- name: Send attack files to the attacker VM
  hosts: attacker
  become: true
  tasks:
    - name: Copy c2_server.py
      ansible.builtin.copy:
        src: ./c2_server.py
        dest: /home/ubuntu/
        mode: '0644'
        owner: ubuntu
        group: ubuntu
      
    - name: Copy stealer_client.py
      ansible.builtin.copy:
        src: ./app/stealer_client.py
        dest: /home/ubuntu/
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Copy BadUSB script
      ansible.builtin.copy:
        src: ./BadUSB.sh
        dest: /home/ubuntu/
        mode: '0644'
        owner: ubuntu
        group: ubuntu


- name: Generate simulated sensible data on the victim VM
  hosts: victim
  become: true
  tasks:
    - name: Copy the script to the vm
      copy:
        src: ./seed_sensitive_files.sh
        dest: /tmp/seed_sensitive_files.sh
        mode: '0755'


- name: Install and configure Wazuh Manager on Wazuh VM
  hosts: wazuh
  become: true

  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add Wazuh GPG key
      ansible.builtin.shell: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
        gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import
      args:
        creates: /usr/share/keyrings/wazuh.gpg

    - name: Set permissions for Wazuh GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/wazuh.gpg
        mode: '0644'

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present

    - name: Install Wazuh Manager
      ansible.builtin.apt:
        name: wazuh-manager
        state: present
        update_cache: yes

    - name: Configure Wazuh Manager (active response)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertafter: '</client>'
        marker: ""
        block: |
          <command>
            <name>firewall-drop</name>
            <executable>firewall-drop.sh</executable>
            <expect>srcip</expect>
            <timeout_allowed>yes</timeout_allowed>
          </command>

          <active-response>
            <command>firewall-drop</command>
            <location>local</location>
            <rules_group>ids</rules_group>
          </active-response>

    - name: Restart and enable Wazuh Manager
      ansible.builtin.service:
        name: wazuh-manager
        state: started
        enabled: true


- name: Install and configure Wazuh Agent on victim VM
  hosts: victim
  become: true
  vars_files:
    - ansible_vars.yaml

  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add Wazuh GPG key
      ansible.builtin.shell: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
        gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import
      args:
        creates: /usr/share/keyrings/wazuh.gpg

    - name: Set permissions for Wazuh GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/wazuh.gpg
        mode: '0644'

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Wazuh Agent
      ansible.builtin.apt:
        name: wazuh-agent
        state: present

    - name: Configure agent to point to manager
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "# {mark} ANSIBLE MANAGER CONFIG"
        insertafter: '</syscheck>'
        block: |
          <client>
            <server>
              <address>{{ wazuh_ip }}</address>
              <port>1514</port>
              <protocol>tcp</protocol>
            </server>
          </client>

    - name: Install iptables-persistent
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
        update_cache: yes

    - name: Save current iptables rules
      ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4